replicaCount: 1

name: economic-times-app
namespace: default

image:
  repository: YOUR_DOCKER_USERNAME/economic-times-app
  tag: latest
  pullPolicy: IfNotPresent

container:
  port: 3000

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30080

resources: {}
